server:
  port: 8090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true #是否自动识别nacos服务
        # 路由规则
      routes:
        - id: order_route # 路由的唯一标识,路由到order服务
#          uri: http://localhost:8082 # 需要转发的地址
          uri: lb://sentinel-feign-privider #lb:使用nacos中的本地负载均衡策略
#           断言规则 用于路由规则的匹配
          predicates:
            - Path=/order-serv/**
#            - IsAuth=xxoo2
#               http://localhost:8090/order-serv/pc/getData 路由到 ↓
#               http://localhost:8082/order-serv/pc/getData
          filters:
            - StripPrefix=1 #去掉第一个路径,去掉后:http://localhost:8082/pc/getData
#            - MyCheck=aaa #自定义过滤器
        #- id: other_route
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
#      scg:
#        fallback:
#          response-body:
#          response-status:
